# These github actions will update Terraform section(s) of README(s), and
# perform linting using pre-commit.
# spell-checker: ignore yamllint chmod
# yamllint disable rule:line-length
---
name: pre-commit

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install terraform-docs
        run: |
          sudo curl -sLo /tmp/terraform-docs-v0.14.1-linux-amd64.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.14.1/terraform-docs-v0.14.1-linux-amd64.tar.gz
          sudo tar -C /tmp -xzf /tmp/terraform-docs-v0.14.1-linux-amd64.tar.gz
          sudo mv /tmp/terraform-docs /usr/local/bin/
          sudo chmod 0755 /usr/local/bin/terraform-docs
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
