# TODO: @memes - disable/remove as needed
# spell-checker: ignore yamllint qemu buildx DOCKERHUB GOARCH
---
# yamllint disable rule:line-length
name: go-release

# yamllint disable-line rule:truthy
on:
  release:
    types: [published]

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          build-args: |
            COMMIT_SHA=${{ github.sha }}
            TAG_NAME=${{ github.event.release.tag_name }}
          # TODO: @memes - set docker hub app correctly
          tags: |
            memes/APP:latest
            memes/APP:${{ github.event.release.tag_name }}
  binary-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["linux", "darwin", "windows"]
        arch: ["amd64"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Build for ${{ matrix.os }} ${{ matrix.arch }}
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLE: 0
          # yamllint disable-line rule:truthy
          GO111MODULE: on
        run: go build -o APP-${{ github.event.release.tag_name }}-${{ matrix.os }}-${{ matrix.arch }}
      - name: "Upload release binaries"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./APP-${{ github.event.release.tag_name }}-${{ matrix.os }}-${{ matrix.arch }}
          asset_name: APP-${{ github.event.release.tag_name }}-${{ matrix.os }}-${{ matrix.arch }}
          asset_content_type: application/octet-stream
